### Import Packages

In [1]:
import numpy as np
from numpy.linalg import inv
np.set_printoptions(precision=4)

### Lattice parameters & Irrational Element

In [2]:
## Lattice Parameters
a, b, c, gamma = [0.5972,0.5944,0.5584,np.deg2rad(90.37)]

## Irrational Element
q3 = (2*a*b*np.cos(gamma) - np.sqrt(a**4 + b**4 + 2*a**2*b**2*np.cos(2*gamma)))/(a**2 - b**2);
print('q3 = ',round(q3,4))

q3 =  -3.0735


### Metric Tensor

In [3]:
G = np.matrix([[a**2,a*b*np.cos(gamma),0],[a*b*np.cos(gamma),b**2,0],[0,0,c**2]])
print(G)

[[ 0.3566 -0.0023  0.    ]
 [-0.0023  0.3533  0.    ]
 [ 0.      0.      0.3118]]


### Transformation Matrix: $V_1 \to R$

In [4]:
rPv1 = np.matrix([[1,b/a*np.cos(gamma),0],[0,-b/a*np.sin(gamma),0],[0,0,-c/a]]);
print(rPv1)

[[ 1.     -0.0064  0.    ]
 [ 0.     -0.9953  0.    ]
 [ 0.      0.     -0.935 ]]


### Correspondence Matrix

In [5]:
C = np.matrix([[0,-1,0],[1,0,0],[0,0,1]])
print(C)

[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]


### shear

In [6]:
s = np.sqrt(np.trace(C.T @ G @ C @ inv(G))-3)
print('s = ', round(s,5))

s =  0.01597


### Non-conventional Twinning Mode

#### Twinning Mode in $V_1 - $frame

In [7]:
## invariant plane
K1 = np.matrix([1,q3,0]);
print('K1 = ', K1)

## shear direction
eta1 = np.matrix([[q3],[-1],[0]]);
print('eta1 = ',eta1)

K1 =  [[ 1.     -3.0735  0.    ]]
eta1 =  [[-3.0735]
 [-1.    ]
 [ 0.    ]]


#### Twinning Mode in $R - $frame

$^R \boldsymbol{l}$ : unit vector parallel to the shear direction

$^R \boldsymbol{m}$ : unit vector normal to the invariant plane


In [8]:
rl = rPv1 @ eta1 #shear direction in R-frame
rl = rl / np.sqrt(rl.T @ rl) #unit vector parallel to shear direction
print(rl)

rm = K1 @ inv(rPv1) #invariant plane in R-frame
rm = rm / np.sqrt(rm @ rm.T) #unit vector normal to invariant plane
print(rm)

[[-0.9512]
 [ 0.3087]
 [ 0.    ]]
[[0.3087 0.9512 0.    ]]


#### Shear Matrix in $R - $frame 

$^RS^i_j = \delta^i_j + s\ ^Rl^i\ ^Rm_j $

In [9]:
## initialize 3 by 3 matrix
rS = np.zeros([3,3])

# Using the einstein notation
#1st row
rS[0,0] = 1 + s * rl.item(0) * rm.item(0) #i=0,j=0
rS[0,1] = 0 + s * rl.item(0) * rm.item(1) #i=0,j=1
rS[0,2] = 0 + s * rl.item(0) * rm.item(2) #i=0,j=2
#2nd row
rS[1,0] = 0 + s * rl.item(1) * rm.item(0) #i=1,j=0
rS[1,1] = 1 + s * rl.item(1) * rm.item(1) #i=1,j=1
rS[1,2] = 0 + s * rl.item(1) * rm.item(2) #i=1,j=2
#3rd row
rS[2,0] = 0 + s * rl.item(2) * rm.item(0) #i=2,j=0
rS[2,1] = 0 + s * rl.item(2) * rm.item(1) #i=2,j=1
rS[2,2] = 1 + s * rl.item(2) * rm.item(2) #i=2,j=2

#convert to matrix and print
rS = np.asmatrix(rS)
print(rS)

[[ 0.9953 -0.0145  0.    ]
 [ 0.0015  1.0047  0.    ]
 [ 0.      0.      1.    ]]


#### Orientation Relationship in $R - $frame

We know,

$\boldsymbol{C}\ =\ ^m\boldsymbol{L}\ ^m \boldsymbol{S}$, 

Thus,

$^R\boldsymbol{L}\ =\ ^R\boldsymbol{P}^m\ \boldsymbol{C}\ ^m\boldsymbol{P}^R\ ^R \boldsymbol{S}^{-1}$

In [10]:
rL = rPv1 @ C @ inv(rPv1) @ inv(rS)
print(rL)

[[-0.008  1.     0.   ]
 [-1.    -0.008  0.   ]
 [ 0.     0.     1.   ]]


In [12]:
a = rL[0,0]
np.degrees(np.arccos(a))

90.4576051266445